<?php
$tr = Zend_Registry::get('Zend_Translate');
?>

<div id="submenu">
  <ul>
    <?php if($this->is_root_company):?>
    <li class="back"><a href="<?php echo $this->url(array('controller' => 'company', 'action' => 'index'), '', true); ?>"><?php echo $tr->_("Back");?></a></li>
    <?php else:?>
    <li class="back"><a href="<?php echo $this->url(array('controller' => 'company', 'action' => 'manage', 'id' => $this->parent_company_id), '', true); ?>"><?php echo $tr->_("Back");?></a></li>
    <?php endif;?>
    <?php if($this->is_root_company):?>
    <li class="add"><a href="<?php echo $this->url(array('controller' => 'company', 'action' => 'add', 'parentcompanyid' => $this->companyid), '', true); ?>"><?php echo sprintf($tr->_("Add new customer for %s"), $this->companyname);?></a></li>
    <?php endif;?>
    <li class="add"><a href="<?php echo $this->url(array('controller' => 'company', 'action' => 'add-branch-office', 'companyid' => $this->companyid), '', true); ?>"><?php echo sprintf($tr->_("Add new branch office for %s"), $this->companyname);?></a></li> 
    <li class="add"><a href="<?php echo $this->url(array('controller' => 'user', 'action' => 'add', 'companyid' => $this->companyid), '', true); ?>"><?php echo sprintf($tr->_("Add new user for %s"), $this->companyname);?></a></li> 
  </ul>
</div>

<br />
<br />
<?php echo $this->companyname;?>
<br />

<img src="<?php echo $this->baseUrl();?>/images/icons/branch-office.png" alt="" border="0" style="float:left; width: 32px; height:32px;" /><h2><?php echo sprintf($tr->_("%s - Branch offices"), $this->companyname);?>:</h2>

<?php echo $this->branches;?>

<?php if(!empty($this->customers)):?>
  <h2><?php echo sprintf($tr->_("%s - Customers"), $this->companyname);?></h2>
  <?php echo $this->customers;?>
<?php endif;?>

<br />

<img src="<?php echo $this->baseUrl();?>/images/icons/tickets.png" alt="" border="0" style="float:left; width: 32px; height:32px;" /><h2><?php echo sprintf($tr->_("%s - Tickets"), $this->companyname);?>:</h2>
TODO

<br />

<h2><?php echo sprintf($tr->_("%s - Networks"), $this->companyname);?>:</h2>
TODO

<br />

<img src="<?php echo $this->baseUrl();?>/images/icons/domain.png" alt="" border="0" style="float:left; width: 32px; height:32px;" /><h2><?php echo sprintf($tr->_("%s - Domains"), $this->companyname);?>:</h2>
TODO
<br />

<img src="<?php echo $this->baseUrl();?>/images/icons/users.png" alt="" border="0" style="float:left; width: 32px; height:32px;" /><h2><?php echo sprintf($tr->_("%s - People"), $this->companyname);?>:</h2>

<?php echo $this->users; ?>
<br />
