<?php
$tr = Zend_Registry::get('Zend_Translate');
?>
<div id="submenu">
  <ul>
    <li class="back"><a href="<?php echo $this->url(array('controller' => 'company', 'action' => 'manage-branch', 'id' => $this->branchid), '', true); ?>"><?php echo $tr->_("Back");?></a></li>
    <li class="add"><a href="<?php echo $this->url(array('controller' => 'company', 'action' => 'add-network-device-port', 'networkdeviceid' => $this->deviceid), '', true); ?>"><?php echo $tr->_("Add port to network device");?></a></li> 
  </ul>
</div>

<br />
<br />
<?php echo $this->companyname;?> &raquo; <?php echo $this->branchname;?> &raquo; <?php echo $this->devicename;?>
<br />

<h2><?php echo $tr->_("Network device's ports");?></h2>

<?php echo $this->grid;?>
