<?php
$tr = Zend_Registry::get('Zend_Translate');
?>

<div id="submenu">
  <ul>
    <li class="back"><a href="<?php echo $this->url(array('controller' => 'company', 'action' => 'manage', 'id' => $this->companyid), '', true); ?>"><?php echo $tr->_("Back");?></a></li> 
  </ul>
</div>


<br />
<br />
<?php echo $this->companyname;?>
<br />

<img src="/images/icons/branch-office.png" alt="" /><h2><?php echo sprintf("Add branch office for company %s", $this->companyname);?> </h2>

<?php echo $this->form;?>
