<?php
$tr = Zend_Registry::get('Zend_Translate');
?>

<a href="<?php echo $this->url(array('controller' => 'index', 'action' => 'login'), '', true); ?>"><?php echo $tr->_("Login page");?></a>
<h2>Reset password</h2>
<table style="margin: auto auto; background-color: #fafafa; padding:1em; -moz-border-radius: 10px; border: 1px solid #000;">
  <tr>
    <td valign="top" width="1">
      <?php echo $this->form;?>
      You'll be redirected to login page upon successful password reset.
    </td>
    <td><img src="/images/icons/login.png" border="0" alt="" /></td>
  </tr>
</table>
