/* -------------------------------------------------------------------------- */
/* GLOBAL */
/* -------------------------------------------------------------------------- */

*
{
  margin: 0;
  padding: 0;
}

html
{
  color: #333;
  background-image: url(/images/layout/background.png);
  background-attachment: fixed;
  background-repeat: repeat-x;
}

hr {
  border: none;
  width: 100%;
  color: #fff;
  background-color: #000;
  height: 1px;
}

img {
	border: none;
}

td a.icon img {
	width: 32px;
	height: 32px;
	margin: auto auto;
}

#menu a img
{
	width: 64px;
	height: 64px;
}

#menu a img:hover
{
  background-color: #ddd;
}


#menu
{
  display: block;
  background-color: #eee;
}

#content
{
  margin: auto auto;
  width: 99%;
}

#footer
{
  margin: auto auto;
  text-align: center;
}

#ssl-status-on
{
  color: #00ff00;
  font-weight: bold;
}

#ssl-status-off
{
  color: #ff0000;
  font-weight: bold;
}

#ssl-status-on, #ssl-status-off
{
  padding: 0.4em;
  border: 1px solid #000;
  background-color: #eee;
}

ul.errors
{
  color: #ff0000;
}

/* -------------------------------------------------------------------------- */
/* GRID */
/* -------------------------------------------------------------------------- */

#paginglinks {
	margin: 5px auto 5px auto;
	clear: both;
}
.pagelink, .pagelinklast, .pagecurrent {
	background: transparent;
	border: 1px solid #212121;
	padding: 1px 3px 1px 3px;
}
.pagelinklast {
	background: #999;
}
.pagecurrent {
	background: #999;
}
div.grid-header-button {
	background-color: transparent;
	text-align: right;
	padding: 0;
	margin: 0;
}
div.grid-header-button input {
	margin: 5px;
}
table.grid {
	border-top: 1px solid #DFDFDF;
	border-right: 1px solid #DFDFDF;
	width: 100%;
	color: #000;
}
tr.rowHead {
	background-color: #eee;
}
tr.rowHead th.first-cell {
	border-left: 1px solid #DFDFDF;
}
tr.rowHead th {
	padding: 5px;
	color: #000;
	font-size: 9pt;
	font-weight: bold;
	border-top: 3px solid #F7F5EE;
	border-bottom: 3px solid #FEBE47;
	border-left: 1px solid #fff;
	background-color: #ECE9D8;
}

tr.rowHead th:hover {
	background-color: #FAF9F4;
	color: #ccc;
}

tr.rowHead th a {
	display: block;
}
tr.rowFoot {
	background-color: #eee;
}
tr.rowFoot td {
	padding: 2px;
	color: #000;
	font-size: 9pt;
	font-weight: bold;
	/*border-top: 3px solid #F7F5EE;
*/
	border-bottom: 2px solid #FEBE47;
	border-left: 1px solid #fff;
	background-color: #ECE9D8;
}
tr.rowFoot td.first-cell {
	border-left: 1px solid #DFDFDF;
}
tr.rowEven {
	background-color: #eee;
}
tr.rowEven:hover, tr.rowOdd:hover {
	background-color: #DDFFDD;
	color: #000000;
}

tr.rowEven td {
	border-bottom: 1px solid #99BAF3;
	border-left: 1px solid #DFDFDF;
	padding: 5px;
}
tr.rowOdd {
	background-color: #fff;
}
tr.rowOdd td {
	border-bottom: 1px solid #99BAF3;
	border-left: 1px solid #DFDFDF;
	padding: 5px;
}

/* -------------------------------------------------------------------------- */
/* SUBMENUS */
/* -------------------------------------------------------------------------- */

#submenu {
	clear: both;

}

#submenu ul {
	clear: both;
	/*background-color: #e0e0e0;*/
	margin: 0;
	padding: 0;
	list-style: none;
	border: none;
	white-space: nowrap;
	height: 128px;
}

#submenu ul li {
	float: left;
	min-width: 128px;
	/*width: 128px;*/
	position: relative;
	white-space: nowrap;
	border: none;
	/*margin: 2px 0 6px 0;*/
	padding: 0;
	line-height: 128px;
	background-repeat: no-repeat;
	height: 100%;
	/*border: 1px solid #000;*/
}

#submenu ul li a {
	white-space: nowrap;
	border: none;
	color: #000;
	/*height: 100%;
	width: 100%;*/
	text-align: top;
	background-color: #fff;
	text-decoration: none;
	/*margin-top: 128px;*/
	text-align: text-bottom;
	/*vertical-align: text-bottom;*/
}

/* SUBMENU BUTTONS */
#submenu ul li.back {
	background-image: url(/images/icons/back.png);
}

#submenu ul li.add {
	background-image: url(/images/icons/add.png);
}

#submenu ul li.document {
	background-image: url(/images/icons/document.png);
}

