*
{
  margin: 0;
  padding: 0;
}

html
{
  color: #333;
  background-image: url(/images/layout/background.png);
  background-attachment: fixed;
  background-repeat: repeat-x;
}

#content
{
  margin: auto auto;
  text-align: center;
}

form
{
  text-align: left;
  margin: 0;
}

#footer
{
  margin: auto auto;
  text-align: center;
  padding-top: 1em;
}

#ssl-status-on
{
  color: #00ff00;
  font-weight: bold;
}

#ssl-status-off
{
  color: #ff0000;
  font-weight: bold;
}

#ssl-status-on, #ssl-status-off
{
  padding: 0.4em;
  border: 1px solid #000;
  background-color: #eee;
} 

ul.errors
{
  color: #ff0000;
}
