<?php
$tr = Zend_Registry::get('Zend_Translate');

if(isset($_SERVER['HTTPS']) && $_SERVER['HTTPS'] == "on")
{
  $ssl_enabled = true;
}
else
{
  $ssl_enabled = false;
}

echo "\x3c?xml version=\"1.0\" encoding=\"UTF-8\"?\x3e\n";
echo $this->doctype() . "\n";
?>
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
<head>
  <title>XoNoiD CRM</title>
  <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
  <?php echo $this->headLink()->appendStylesheet($this->baseUrl() . '/css/login'); ?> 
</head>
<body>

  <h1 style="position: absolute; top: 1em; right: 1em;">XoNoiD CRM</h1>
  
  <div id="content">
    <?php echo $this->layout()->content; ?>
  </div>

  <div id="footer">
    <span id="ssl-status-<?php echo ($ssl_enabled ? 'on' : 'off');?>"><abbr title="<?php echo $tr->_("Secure Socket Layer");?>"><?php echo $tr->_("SSL");?></abbr> <?php echo $tr->_("Encryption:");?> <?php echo ($ssl_enabled ? $tr->_("Enabled") : $tr->_("Disabled"));?></span>
    <a href="http://framework.zend.com/"><img src="<?php echo $this->baseUrl();?>/images/misc/PoweredBy_ZF_4LightBG.png" alt="" border="0" /></a><br />
  </div>

</body>
</html>
