/* -------------------------------------------------------------------------- */
/* GLOBAL */
/* -------------------------------------------------------------------------- */

html
{
  color: #f0f060;
  background-image: url(/images/layout/background.png);
}

hr {
  border: none;
  width: 99%;
  color: #fff;
  background-color: #000;
  height: 1px;
}

img {
	border: none;
}

td a.icon img {
	width: 32px;
	height: 32px;
	margin: auto auto;
}

#menu a img
{
	width: 64px;
	height: 64px;
}

/* -------------------------------------------------------------------------- */
/* GRID */
/* -------------------------------------------------------------------------- */

#paginglinks {
	margin: 5px auto 5px auto;
	clear: both;
}
.pagelink, .pagelinklast, .pagecurrent {
	background: transparent;
	border: 1px solid #212121;
	padding: 1px 3px 1px 3px;
}
.pagelinklast {
	background: #999;
}
.pagecurrent {
	background: #999;
}
div.grid-header-button {
	background-color: transparent;
	text-align: right;
	padding: 0;
	margin: 0;
}
div.grid-header-button input {
	margin: 5px;
}
table.grid {
	border-top: 1px solid #DFDFDF;
	border-right: 1px solid #DFDFDF;
	width: 100%;
	color: #000;
}
tr.rowHead {
	background-color: #eee;
}
tr.rowHead th.first-cell {
	border-left: 1px solid #DFDFDF;
}
tr.rowHead th {
	padding: 5px;
	color: #000;
	font-size: 9pt;
	font-weight: bold;
	border-top: 3px solid #F7F5EE;
	border-bottom: 3px solid #FEBE47;
	border-left: 1px solid #fff;
	background-color: #ECE9D8;
}
tr.rowHead th:hover {
	background-color: #FAF9F4;
	color: #ccc;
}
tr.rowHead th a {
	display: block;
}
tr.rowFoot {
	background-color: #eee;
}
tr.rowFoot td {
	padding: 2px;
	color: #000;
	font-size: 9pt;
	font-weight: bold;
	/*border-top: 3px solid #F7F5EE;
*/
	border-bottom: 2px solid #FEBE47;
	border-left: 1px solid #fff;
	background-color: #ECE9D8;
}
tr.rowFoot td.first-cell {
	border-left: 1px solid #DFDFDF;
}
tr.rowEven {
	background-color: #eee;
}
tr.rowEven:hover {
	background-color: #FFFFDD;
	color: #000000;
}
tr.rowEven td {
	border-bottom: 1px solid #99BAF3;
	border-left: 1px solid #DFDFDF;
	padding: 5px;
}
tr.rowOdd {
	background-color: #fff;
}
tr.rowOdd:hover {
	background-color: #D9E8F9;
	color: #000000;
}
tr.rowOdd td {
	border-bottom: 1px solid #99BAF3;
	border-left: 1px solid #DFDFDF;
	padding: 5px;
}

/* -------------------------------------------------------------------------- */
/* SUBMENUS */
/* -------------------------------------------------------------------------- */

#submenu {
	clear: both;
}

#submenu ul {
	clear: both;
	/*background-color: #e0e0e0;*/
	margin: 0;
	padding: 0;
	list-style: none;
	border: none;
	white-space: nowrap;
	height: 128px;
}

#submenu ul li {
	float: left;
	width: 128px;
	position: relative;
	white-space: nowrap;
	border: none;
	margin: 2px 0 6px 0;
	padding: 0;
	line-height: 128px;
	background-repeat: no-repeat;
}

#submenu ul li a {
	white-space: nowrap;
	border: none;
	color: #000;
	height: 100%;
	width: 100%;
}

/* SUBMENU BUTTONS */
#submenu ul li.back {
	background-image: url(/images/icons/back.png);
}

#submenu ul li.add {
	background-image: url(/images/icons/add.png);
}
